# Generated by Django 5.2.7 on 2025-10-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_alter_studentmodel_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=80)),
                ('emp_id', models.IntegerField(default=0)),
                ('emp_dept', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('10AM-12PM', '10AM to 12PM'), ('12PM-2PM', '12PM to 2PM'), ('4PM-6PM', '4PM to 6PM'), ('6PM-8PM', '6PM to 8PM')], max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Tutor.employeemodel')),
            ],
        ),
    ]
