# Generated by Django 5.2.7 on 2025-10-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
